### ISSUE TITLE
Attach photo to sms

### ISSUE THREAD

**Issue by squirej** [omorandi/TiSMSDialog#12]
Is there a way to attach a photo to the sms?

**Comment by omorandi** [comment]
Not in the current implementation of the module, though since iOS 7 the MFMessageComposeViewController class supports an [attachments property](https://developer.apple.com/library/ios/documentation/MessageUI/Reference/MFMessageComposeViewController_class/Reference/Reference.html#//apple_ref/doc/uid/TP40009668-CH1-SW18).
The module could be extended in order to support it.

**Comment by omorandi** [comment]
please checkout the latest release where I added attachments support (8276be16ad27fd727f3b41478cc5fa61a07baee7)
