### ISSUE TITLE
TiSMSDialog not compatible with 1.7.0.

### ISSUE THREAD

**Issue by dkrusenstrahle** [omorandi/TiSMSDialog#2]
Hello!

First of all, thank you for a fantastic module.
It works perfectly fine with Appcelerator iOS SDK 1.6.2 but now when I have upgraded to 1.7.0 I cannot create a build for this version. When will the module be compatible with 1.7.0?

Thanks!

**Comment by omorandi** [comment]
Hi,
you should be able to either use the same module binary you created with 1.6.2 with the new release of the SDK, or build it through build.py from source just changing the SDK version in the titanium.xconfig file.
What kind of problems did you encounter?
Bye,

   Olivier

**Comment by omorandi** [comment]
Now the master branch supports 1.7.1 and above. For any version of the Ti SDK between 1.4.3 and 1.7.0, you should check out the Ti-1.6.2 branch. The README notice states that the titanium.xconfig file should be updated accordingly to the actual version of the installed Titanium SDK(s).
Since I haven't heard you for a while I close this issue. Feel free to open a new one if you encounter any problem.
Thanks!
